# (generated with --quick)

from typing import Any

deck: Deck
random: module

class Card:
    color: Any
    value: Any
    def __eq__(self, other) -> bool: ...
    def __init__(self, color, value) -> None: ...
    def __str__(self) -> str: ...

class Deck:
    items: list
    def __init__(self) -> None: ...
    def add(self, item) -> None: ...
    def all_the_same_color(self) -> bool: ...
    def draw(self) -> Any: ...
